[FIX] : Removing the Tier2_HWInventory table section of DbChgTimestamp
unifiedcontrolsystem/dai-ds pull request #219
Opened 2020-10-16 19:45 UTC by nsai1

Signed-off-by: Naian Sai <naian.sai@intel.com>

2020-10-16 22:47 UTC, sindhu-106 requested changes
If we do not use this section any more. Can we delete this section instead of commenting. Because we may need to do clean up again.

2020-10-16 23:23 UTC, nbwhite commented
> If we do not use this section any more. Can we delete this section instead of commenting. Because we may need to do clean up again.

2020-10-16 23:24 UTC, nbwhite approved these changes
I think it's okay to comment this out for now, I believe that this line is intended to work with the reverted changes to the tier2 schema, so we may want it later.

2020-10-19 14:42 UTC, paul-amonson approved these changes

2020-10-19 16:57 UTC, sindhu-106 approved these changes

2020-10-19 18:39 UTC, merged