[Fix] Adding new AdapterDaiMgr and tests.
unifiedcontrolsystem/dai-ds pull request #249
Opened 2020-11-30 21:27 UTC by paul-amonson

Signed-off-by: Paul Amonson <paul.d.amonson@intel.com>

2020-11-30 21:59 UTC, sindhu-106 requested changes

2020-11-30 21:59 UTC, sindhu-106 commented on build.gradle
> +                    minimum = 0.50
Is this okay ?

2020-11-30 22:00 UTC, paul-amonson commented on build.gradle
> +                    minimum = 0.50
Yes, I ran it by @nbwhite first. :)

2020-11-30 22:20 UTC, nbwhite commented on build.gradle
> +                    minimum = 0.50
Confirmed, this is fine, we've got enough wiggle room elsewhere.

2020-11-30 23:46 UTC, sindhu-106 submitted a review, later dismissed

2020-12-01 16:57 UTC, sindhu-106 submitted a review, later dismissed

2020-12-02 15:41 UTC, paul-amonson commented
Last push addressed the change in MachineConfig.json files.

2020-12-02 17:45 UTC, sindhu-106 submitted a review, later dismissed

2020-12-02 17:56 UTC, nbwhite commented on config-files/MachineConfig.json
>        "ServiceNode":"SN0-SMS1",
Is this change running up against the security issue we had before with command line invocations?

2020-12-02 18:01 UTC, paul-amonson commented on config-files/MachineConfig.json
>        "ServiceNode":"SN0-SMS1",
I am not sure as we are not using the CheckMarx static analysis anymore. We will need to see what Klocwork's says.

2020-12-02 20:19 UTC, sindhu-106 approved these changes

2020-12-02 20:54 UTC, nbwhite approved these changes
Confirmed, this fixes the DAIManager restart bug.

2020-12-02 21:15 UTC, merged