[Feat] New Rpms for new authentication method.
unifiedcontrolsystem/dai-ds pull request #260
Opened 2021-01-04 18:25 UTC by paul-amonson

[Feat] Replacement keycloak token retriever.
[Feat] Added a new task to run Python Tests for the ucs cli.

Signed-off-by: Paul Amonson <paul.d.amonson@intel.com>

2021-01-07 18:02 UTC, sindhu-106 requested changes

2021-01-07 18:04 UTC, avincigu submitted a review, later dismissed

2021-01-07 18:04 UTC, avincigu commented on build.gradle
> +// Test the Python cli code (manual test)                                              //
I like this, not sure if it runs as part of the build?

2021-01-07 21:01 UTC, paul-amonson commented on units.pipeline.groovy
> +                        archiveArtifacts allowEmptyArchive: false, artifacts: 'build/distributions/*.**'
Ask @cmcheung-UCS I am most sure I followed his suggestion.

2021-01-07 21:02 UTC, paul-amonson commented on foreign_bus/src/main/java/com/intel/dai/foreign_bus/CommonFunctions.java
> +            if(tmp != null)
I am not sure anymore but it may be a mute point moving forward.

2021-01-07 21:02 UTC, paul-amonson commented on build.gradle
> +// Test the Python cli code (manual test)                                              //
It is not, Travis CI fails to run the tests correctly. This is a manual Task.

2021-01-08 15:17 UTC, paul-amonson commented on foreign_bus/src/main/java/com/intel/dai/foreign_bus/CommonFunctions.java
> +            if(tmp != null)
Ok after researching and asking, Leo suggested we not use the strings specified.

2021-01-08 16:35 UTC, cmcheung-UCS commented on units.pipeline.groovy
> +                        archiveArtifacts allowEmptyArchive: false, artifacts: 'build/distributions/*.**'
** means everything under the parent directory.  This includes subdirectories and content of subdirectories.  * just means the files in the directory.

2021-01-11 16:36 UTC, avincigu approved these changes

2021-01-11 20:44 UTC, sindhu-106 approved these changes

2021-01-11 23:51 UTC, merged