Readd Benchmarking to NearlineTier
unifiedcontrolsystem/dai-ds pull request #280
Opened 2021-02-25 01:10 UTC by nbwhite

Signed-off-by: Nathan B White <nathan.b.white@intel.com>

2021-02-25 12:57 UTC, avincigu approved these changes

2021-02-25 15:27 UTC, paul-amonson requested changes
See e-mail I sent to @nbwhite . :)

2021-02-25 18:28 UTC, paul-amonson commented
Ok, so it looks like the "static" hostname is returned first. The other information is from DNS and is "dynamic" hostname information. Fixed the code.

2021-02-26 14:34 UTC, avincigu approved these changes

2021-02-26 15:02 UTC, paul-amonson approved these changes

2021-02-26 18:23 UTC, merged