[FIX] : First pass at merging code bases, removing unused tables and …
unifiedcontrolsystem/dai-ds pull request #284
Opened 2021-02-26 23:08 UTC by nsai1

…repeating function calls.

Signed-off-by: Naian Sai <naian.sai@intel.com>

2021-02-26 23:14 UTC, sindhu-106 approved these changes

2021-02-26 23:55 UTC, nbwhite approved these changes

2021-03-01 15:20 UTC, paul-amonson requested changes
Are these also being removed from PO? We need the files to be at least close to each other.

2021-03-01 16:53 UTC, nsai1 commented
> Are these also being removed from PO? We need the files to be at least close to each other.

Oh no, they are not required, but alright i see the point now, I will include them back. Is there an easy way to do that now?

2021-03-01 17:00 UTC, closed without merging