Raw inventory history fixes.
unifiedcontrolsystem/dai-ds pull request #296
Opened 2021-03-15 20:57 UTC by cmcheung-UCS

2021-03-15 21:46 UTC, avincigu submitted a review, later dismissed

2021-03-15 22:16 UTC, paul-amonson requested changes
See e-mail.

2021-03-15 22:48 UTC, paul-amonson commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierVolt.java
> +        mEntryNumber_RAWHWINVENTORY_HISTORY         = -99999L;
Should these changes also be in the Jdbc implementation file as well or are they specific to Volt?

2021-03-16 15:02 UTC, closed without merging

2021-03-16 15:02 UTC, cmcheung-UCS commented
Resubmit later.