[Merge] Updated common code merge.
unifiedcontrolsystem/dai-ds pull request #321
Opened 2021-05-21 15:42 UTC by paul-amonson

Signed-off-by: Paul Amonson <paul.d.amonson@intel.com>

2021-05-21 17:13 UTC, nbwhite approved these changes

2021-05-25 00:25 UTC, sindhu-106 submitted a review, later dismissed

2021-05-25 00:25 UTC, sindhu-106 commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
can we add java.sql to import packages ?

2021-05-25 13:59 UTC, paul-amonson commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
So, not sure what you are asking here...it wouldn't compile if the java.sql was not imported?

2021-06-03 17:57 UTC, nbwhite approved these changes

2021-06-03 17:57 UTC, nbwhite commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
I think the question here is: why do we need to have java.sql in front of the Connection?

2021-06-03 18:28 UTC, paul-amonson commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
Because that is the way it was in the other repo. I did not add it.

2021-06-07 12:34 UTC, avincigu requested changes

2021-06-07 12:34 UTC, avincigu commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
Can we skip this file in this merge? This is a revert of a change I made before sabbatical. This will probably go back in this week.

2021-06-07 12:34 UTC, avincigu commented on dai_core/src/main/java/com/intel/dai/NearlineTableUpdater.java
> +        mConn = tier2DbConn;
Same here. Please skip this file for this merge.

2021-06-07 12:34 UTC, avincigu commented on dai_core/src/test/java/com/intel/dai/AdapterNearlineTierJdbcTest.java
> +        @Override
Same here, please skip this file

2021-06-07 12:34 UTC, avincigu commented on dai_core/src/test/java/com/intel/dai/NearlineTableUpdaterTest.java
> +        NearlineTableUpdater updater = new NearlineTableUpdater(connection, log_);
Same here, please skip this file.

2021-06-07 12:34 UTC, avincigu commented on data/db/DAI-Tier2-Schema-Psql.sql
> +CREATE OR REPLACE FUNCTION public.getinventorychange(p_start_time timestamp without time zone, p_end_time timestamp without time zone, p_lctn character varying, p_limit integer) RETURNS SETOF public.
Please don't change these functions as they will break the CLI. We discussed this stores procedures previously, but maybe we can discuss a solution so they are easy to identify and they don't cause confusion as they are now. Let's sync before merging this.

2021-06-07 13:57 UTC, paul-amonson commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
If we skip this merge other files will be out of sync.

2021-06-07 14:24 UTC, avincigu commented on dai_core/src/main/java/com/intel/dai/AdapterNearlineTierJdbc.java
> +    java.sql.Connection createConnection() throws DataStoreException {
Yes but just for a week, and then in a weeks time they will look exactly the same, we can merge it, but in my opinion it will just be extra work.

2021-06-07 15:03 UTC, avincigu approved these changes

2021-06-07 17:04 UTC, nbwhite approved these changes

2021-06-07 17:04 UTC, merged