[FEAT] boot image information from console log data
unifiedcontrolsystem/dai-ds pull request #324
Opened 2021-06-17 22:23 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2021-06-17 22:49 UTC, paul-amonson requested changes

2021-06-17 22:49 UTC, paul-amonson commented on configurations/eventsim/ProviderProvisionerNetworkForeignBus.json
> +    "consolelog": "ConsoleLogData"
This map should be static. Why aren't you using "logs" which was designed for logs in CommonData format?  Anyway, these aren't added to the enum mapping in DataType in the DAI Network Listener component.  As a side note the plan is to move this to resources (just haven't got to it yet).

2021-06-18 17:14 UTC, paul-amonson submitted a review, later dismissed

2021-06-18 17:15 UTC, paul-amonson commented on configurations/eventsim/ProviderProvisionerNetworkForeignBus.json
> +    "consolelog": "ConsoleLogData"
Handle this with a separate review. :)

2021-06-18 17:44 UTC, yhuan47 submitted a review, later dismissed

2021-06-18 18:14 UTC, sindhu-106 commented on configurations/eventsim/ProviderProvisionerNetworkForeignBus.json
> +    "consolelog": "ConsoleLogData"
sure Paul

2021-06-18 18:19 UTC, paul-amonson approved these changes

2021-06-21 18:58 UTC, avincigu approved these changes

2021-06-21 19:03 UTC, paul-amonson commented
I will be merging this without the checks completed. It seems travis-ci.org was deprecated. Working on getting travis-ci.com functioning.

2021-06-21 19:03 UTC, merged