[FEAT] data parse store and monitor syslog data
unifiedcontrolsystem/dai-ds pull request #352
Opened 2021-07-14 22:45 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2021-07-14 23:02 UTC, paul-amonson commented on configurations/aurora/ProviderMonitoringNetworkForeignBus.json
> +        "topics": "sensors_node,SYSLOG"
This is a Ras Event not a sensor telemetry. Use the section with "sel_log".

2021-07-14 23:02 UTC, paul-amonson commented on monitoring/src/main/java/com/intel/dai/monitoring/EnvironmentalProviderHPCM.java
> +            processorMap_.put("SYSLOG", new TopicMetricSyslog(log_, doAggregation));
Same here: This is a Ras Event not a sensor telemetry. Use the section with "sel_log".

2021-07-14 23:02 UTC, paul-amonson commented on monitoring/src/main/java/com/intel/dai/monitoring/TopicMetricSyslog.java
> +package com.intel.dai.monitoring;
Model after the parser for RasEvents not Metrics.

2021-07-14 23:03 UTC, paul-amonson requested changes
Address overall design issue.

2021-07-15 18:16 UTC, sindhu-106 commented on configurations/aurora/ProviderMonitoringNetworkForeignBus.json
> +        "topics": "sensors_node,SYSLOG"
moved to ras event monitoring

2021-07-15 19:25 UTC, sindhu-106 commented
> Address overall design issue.

made changes you suggested.

2021-07-15 19:44 UTC, paul-amonson commented on monitoring/src/main/java/com/intel/dai/monitoring/TopicEventSyslog.java
> +                log_.warn("Error: ", e.getMessage());
log_warn("Error: %s", e.getMessage());

2021-07-15 20:56 UTC, paul-amonson submitted a review, later dismissed

2021-07-15 21:31 UTC, sindhu-106 commented on monitoring/src/main/java/com/intel/dai/monitoring/TopicEventSyslog.java
> +                log_.warn("Error: ", e.getMessage());
good catch Paul. Will update it :)

2021-07-16 12:11 UTC, avincigu approved these changes

2021-07-16 16:17 UTC, paul-amonson approved these changes

2021-07-16 16:46 UTC, merged