Install script changes for HPCM install.
unifiedcontrolsystem/dai-ds pull request #409
Opened 2021-08-31 21:44 UTC by paul-amonson

2021-09-01 17:41 UTC, nbwhite approved these changes

2021-09-01 18:20 UTC, nbwhite requested changes

2021-09-01 18:20 UTC, nbwhite commented on scripts/hpcm-daids-install.sh
> +if [ -z $(cm repo show | grep "* ${REPO_NAME} : ${DIR}/repos/${REPO_NAME}") ]; then
These brackets need to be double, ("[[ ]]") or this line will fail.

2021-09-01 20:36 UTC, nbwhite submitted a review, later dismissed

2021-09-01 20:36 UTC, nbwhite commented on scripts/hpcm-daids-install.sh
> +  cp /tmp/dai-*.rpm "${DIR}/repos/${REPO_NAME}/"
This line only works if the rpms have been copied into /tmp directly. That step is not included in the script or in the documentation.

2021-09-07 23:36 UTC, avincigu submitted a review, later dismissed

2021-09-08 14:34 UTC, avincigu submitted a review, later dismissed

2021-09-08 23:12 UTC, nbwhite approved these changes

2021-09-09 00:56 UTC, sindhu-106 approved these changes

2021-09-09 11:31 UTC, avincigu approved these changes

2021-09-09 14:08 UTC, merged