[FEAT] do not change state directly from active to dhcpdiscovered
unifiedcontrolsystem/dai-ds pull request #410
Opened 2021-09-01 17:20 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2021-09-01 18:24 UTC, avincigu approved these changes

2021-09-01 18:26 UTC, paul-amonson approved these changes

2021-09-01 18:37 UTC, anpatel1 approved these changes

2021-09-01 18:53 UTC, anpatel1 requested changes

2021-09-01 18:53 UTC, anpatel1 commented on procedures/src/main/java/com/intel/dai/procedures/ComputeNodeSetStates.java
> +            if ((sNodeNewState.equals("D")) && (aNodeData[0].getString("State").equals("A"))) {
Instead of ignoring the DHCP requests message, you should raise a RAS event if the MAC address in DHCPDISCOVER message is not part of dai-ds configuration.

2021-09-01 19:02 UTC, paul-amonson commented on procedures/src/main/java/com/intel/dai/procedures/ComputeNodeSetStates.java
> +            if ((sNodeNewState.equals("D")) && (aNodeData[0].getString("State").equals("A"))) {
So EVERY networked equipment MUST be in our manifest? What if its not? RAS events will be fired that are not errors.

2021-09-02 17:58 UTC, anpatel1 approved these changes

2021-09-02 18:01 UTC, paul-amonson approved these changes

2021-09-02 18:59 UTC, merged