[FEAT] raise ras event for node down/active
unifiedcontrolsystem/dai-ds pull request #475
Opened 2021-11-01 21:00 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2021-11-01 23:24 UTC, anpatel1 approved these changes

2021-11-02 03:14 UTC, yhuan47 approved these changes

2021-11-02 14:31 UTC, paul-amonson commented on dai_core/src/main/java/com/intel/dai/dsapi/BootState.java
> -    NODE_ONLINE,
Why are you removing this everywhere?

2021-11-02 14:32 UTC, paul-amonson requested changes
Removing NODE_ONLINE should not be done. It is a valid state. i.e. Node has power but the OS is halted.

2021-11-02 14:37 UTC, sindhu-106 commented on dai_core/src/main/java/com/intel/dai/dsapi/BootState.java
> -    NODE_ONLINE,
to maintain consistency Paul

2021-11-02 16:23 UTC, paul-amonson approved these changes

2021-11-02 16:34 UTC, anpatel1 commented on dai_core/src/test/java/com/intel/dai/dsimpl/voltdb/VoltDbAdapterOperationsTest.java
>          operations.markNodeState(BootState.NODE_ONLINE, "location", System.currentTimeMillis() * 1000, true);
Arent these two same lines and redundant?

2021-11-02 16:49 UTC, yhuan47 approved these changes

2021-11-02 16:53 UTC, anpatel1 approved these changes

2021-11-02 17:40 UTC, merged