[FIX] mapping correct loc to mac data
unifiedcontrolsystem/dai-ds pull request #510
Opened 2021-12-08 23:31 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2021-12-08 23:35 UTC, nbwhite approved these changes

2021-12-08 23:48 UTC, paul-amonson requested changes
So I am not comfortable with these changes, Its seems that instead of adding the new needed methods the current ones are being changed.  Will this break other functionality?

2021-12-08 23:52 UTC, sindhu-106 commented
> So I am not comfortable with these changes, Its seems that instead of adding the new needed methods the current ones are being changed. Will this break other functionality?

"bmcmacaddr" is used only for eventsim to get mac-addr which is incorrect, changing it to macaddr from bmcmacaddr

2021-12-09 15:25 UTC, paul-amonson approved these changes
Ok after looking at your original commit in September I see what your mistake was. You added the "BMCMAC" features but named the functions as just "MAC" features. This misnaming is what caused me to pause on this review. This new commit makes the implementation and naming consistent.  :) If I am wrong about consistent please sure it is. :)

2021-12-09 17:49 UTC, avincigu approved these changes

2021-12-09 17:54 UTC, yhuan47 approved these changes

2021-12-09 18:21 UTC, merged