Add option to show all dependencies
unifiedcontrolsystem/dai-ds pull request #524
Opened 2022-01-06 00:17 UTC by nbwhite

Signed-off-by: Nathan B White <nathan.b.white@intel.com>

2022-01-06 01:36 UTC, cmcheung-UCS approved these changes

2022-01-06 01:53 UTC, sindhu-106 approved these changes

2022-01-06 14:17 UTC, avincigu submitted a review, later dismissed

2022-01-06 15:10 UTC, paul-amonson commented on build.gradle
> +    task allDeps(type: DependencyReportTask) {}
Why not add to the existing allprojects section just above this?

2022-01-06 15:11 UTC, paul-amonson requested changes
Why can't the new task definition be in the current allprojects section?

2022-01-06 18:36 UTC, nbwhite commented
> Why can't the new task definition be in the current allprojects section?

I wasn't sure if that would work, not knowing gradle all that well. I can try it out and see if it works

2022-01-06 18:39 UTC, paul-amonson approved these changes

2022-01-07 00:17 UTC, sindhu-106 approved these changes

2022-01-07 00:24 UTC, merged