[Fix] Updated groovy and junit versions, fixed test errors.
unifiedcontrolsystem/dai-ds pull request #530
Opened 2022-01-20 17:23 UTC by paul-amonson

Signed-off-by: Paul Amonson <paul.d.amonson@intel.com>

2022-01-20 18:27 UTC, yhuan47 submitted a review, later dismissed

2022-01-20 23:06 UTC, nbwhite requested changes

2022-01-20 23:06 UTC, nbwhite commented on build.gradle
> +def mockito = '4.2.0'                     // Added 01/20/2022
These should be junit_version & mockito_version for consistency.

2022-01-21 15:19 UTC, paul-amonson commented on build.gradle
> +def mockito = '4.2.0'                     // Added 01/20/2022
Fixed. :)

2022-01-21 18:14 UTC, nbwhite approved these changes

2022-01-24 17:27 UTC, avincigu approved these changes

2022-01-24 19:04 UTC, merged