Integration of ras events from PO provisioner to dai-ds
unifiedcontrolsystem/dai-ds pull request #538
Opened 2022-01-31 16:51 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2022-01-31 21:00 UTC, paul-amonson approved these changes

2022-01-31 21:05 UTC, paul-amonson requested changes
Sorry, but you need to change the Aurora.yml files for aurora and aurora-tds configurations don't forget the Australis.yml file as well. Your changed will be wiped out when I regenerate the json files again.

2022-02-01 19:01 UTC, paul-amonson approved these changes

2022-02-01 21:14 UTC, avincigu approved these changes

2022-02-01 21:15 UTC, merged