[FEAT] Add provider to monitor cool device metrics
unifiedcontrolsystem/dai-ds pull request #624
Opened 2022-03-31 05:18 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2022-06-07 18:48 UTC, avincigu submitted a review, later dismissed

2022-06-08 17:23 UTC, yhuan47 approved these changes

2022-06-08 22:24 UTC, yhuan47 approved these changes

2022-06-08 22:26 UTC, nbwhite requested changes

2022-06-08 22:26 UTC, nbwhite commented on configurations/aurora/scripts/Australis.yml
> +>>>>>>> [FEAT] Add provider to monitor cool device metrics
Looks like  missed merge here.

2022-06-08 22:26 UTC, nbwhite commented on configurations/aurora/scripts/Borealis.yml
> +>>>>>>> [FEAT] Add provider to monitor cool device metrics
Another missed merge here

2022-06-09 00:43 UTC, sindhu-106 commented on configurations/aurora/scripts/Borealis.yml
> +>>>>>>> [FEAT] Add provider to monitor cool device metrics
good catch Nathan

2022-06-09 21:18 UTC, merged