Adding job step processing
unifiedcontrolsystem/dai-ds pull request #682
Opened 2022-06-16 18:12 UTC by avincigu

2022-06-16 20:42 UTC, sindhu-106 requested changes

2022-06-16 20:42 UTC, sindhu-106 commented on configurations/aurora-tds/AdapterWlmPBS.json
> +  "topics": "pbs_runjobs,pbs_jobsteps"
could you add these changes to yaml files too

2022-06-17 17:58 UTC, sindhu-106 approved these changes

2022-06-22 00:01 UTC, yhuan47 approved these changes

2022-07-21 17:12 UTC, merged