[FEAT] add provider to monitor cray elerts
unifiedcontrolsystem/dai-ds pull request #692
Opened 2022-07-18 20:31 UTC by sindhu-106

Signed-off-by: sindhuja <sindhuja.gajula@intel.com>

2022-07-19 22:19 UTC, nbwhite approved these changes

2022-07-20 22:53 UTC, yhuan47 commented on configurations/common/RasEventMetaData.json
> +        "DescriptiveName":"RasCrayAlertError",
Could you make the RAS event type more specific? sth like RasCrayExAlertThresholdError. In case we have more type of alerts in the future. RasCrayExAlertThresholdWarn, RasCrayExAlertThresholdInfo

2022-07-22 18:44 UTC, yhuan47 approved these changes

2022-07-25 17:58 UTC, nbwhite approved these changes

2022-08-02 23:16 UTC, nbwhite submitted a review, later dismissed
New feature has been tested with simulation data.

2022-08-03 22:59 UTC, yhuan47 approved these changes

2022-08-04 17:30 UTC, nbwhite requested changes

2022-08-04 17:30 UTC, nbwhite commented on configurations/aurora-tds/ProviderMonitoringNetworkForeignBus.json
> +        "event_cooldev"
Looks like log_sel got deleted in the merge

2022-08-04 17:33 UTC, sindhu-106 commented on configurations/aurora-tds/ProviderMonitoringNetworkForeignBus.json
> +        "event_cooldev"
no Nathan. It is the first one.

2022-08-04 17:36 UTC, nbwhite approved these changes

2022-08-04 18:21 UTC, nbwhite approved these changes

2022-08-04 18:27 UTC, yhuan47 approved these changes

2022-08-04 23:39 UTC, merged