[Chore] Updated aurora configuration for HPCM 1.8
unifiedcontrolsystem/dai-ds pull request #774
Opened 2023-01-20 21:42 UTC by nbwhite

Signed-off-by: Nathan B White <nathan.b.white@intel.com>

2023-01-20 22:01 UTC, VanshIntel approved these changes

2023-01-26 00:25 UTC, sindhu-106 requested changes

2023-01-26 00:25 UTC, sindhu-106 commented on configurations/aurora/ProviderMonitoringNetworkForeignBus.json
> -        "crayex_telemetry"
is the kafka-topic name changed from crayex_telemetry to crayex_aurora-telemetry-00 ?

2023-01-26 00:33 UTC, nbwhite commented on configurations/aurora/ProviderMonitoringNetworkForeignBus.json
> -        "crayex_telemetry"
Good catch, find and replace error

2023-01-30 22:14 UTC, sindhu-106 approved these changes

2023-01-31 19:36 UTC, VanshIntel approved these changes

2023-01-31 19:37 UTC, anpatel1 approved these changes

2023-01-31 21:02 UTC, merged