[FIX]-add IEH errors to pattern filter/match
unifiedcontrolsystem/dai-ds pull request #782
Opened 2023-02-04 00:39 UTC by VanshIntel

2023-02-04 00:49 UTC, nbwhite commented on configurations/aurora/ProviderMonitoringNetworkForeignBus.json
> +            ".*IEH.*Sev:.*IEH FATAL ERROR.*"
Forgot to mention, this list is in priority order, so the new patterns need to at least be above the "priority" entries.

2023-02-06 15:58 UTC, nbwhite requested changes
The new signatures are still below the previous signatures in the patternFilters section

2023-02-06 18:31 UTC, nbwhite approved these changes

2023-02-06 22:06 UTC, sindhu-106 approved these changes

2023-02-07 18:03 UTC, nbwhite approved these changes

2023-02-07 18:03 UTC, nbwhite approved these changes

2023-02-07 18:03 UTC, merged