add DataReceivedTimeStamp into rasEvent
unifiedcontrolsystem/dai-ds pull request #790
Opened 2023-03-17 00:16 UTC by VanshIntel

2023-03-27 23:17 UTC, sindhu-106 requested changes

2023-03-27 23:17 UTC, sindhu-106 commented on networking/src/main/java/com/intel/networking/sink/for_benchmarking/NetworkDataSinkBenchmark.java
> +            callback_.processIncomingData(publishedSubject_, line, 0L);
Why we are sending 0L as created timestamp ?

2023-03-27 23:17 UTC, sindhu-106 commented on networking/src/main/java/com/intel/networking/sink/sse/NetworkDataSinkEventSource.java
> +            callback_.processIncomingData(event, message, 0L);
same here

2023-03-27 23:17 UTC, sindhu-106 commented on fabric/src/main/java/com/intel/dai/fabric/FabricPerfTelemetryProvider.java
>          if(matchSubject(subject)) {
If we are not using the variable please avoid to use as an argument

2023-03-27 23:17 UTC, sindhu-106 commented on fabric/src/main/java/com/intel/dai/fabric/FabricCritTelemetryProvider.java
> +    final protected void processRawMessage(String subject, String message, long dataReceivedTimeStamp) {
What is the use of this variable ? If we are creating current timestamp later ?

2023-03-27 23:17 UTC, sindhu-106 commented on dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
> +                logMissingLocationEvent(eventName, nsTimestamp, dataReceivedTimeStamp);
Error timestamp should be current

2023-03-27 23:17 UTC, sindhu-106 commented on dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
> +                        adapter_.getType(), adapter_.getBaseWorkItemId(), TimeUtils.nanosecondsToMicroseconds(TimeUtils.getNsTimestamp()));
use passed value should be used to create ras event

2023-03-28 18:52 UTC, sindhu-106 requested changes

2023-03-28 18:52 UTC, sindhu-106 commented on provisioners/src/test/java/com/intel/dai/provisioners/NetworkListenerProviderForeignBusTest.java
> +import com.intel.runtime_utils.TimeUtils;
Please remove changes if package is not used in the class

2023-03-28 18:52 UTC, sindhu-106 commented on provisioners/src/main/java/com/intel/dai/provisioners/ElasticsearchDataIngesterThread.java
> +import com.intel.runtime_utils.TimeUtils;
Please remove changes if package is not used in the class

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/test/java/com/intel/dai/monitoring/EventSimEnvironmentalProviderForeignBusTest.java
> +import com.intel.runtime_utils.TimeUtils;
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/test/groovy/com/intel/dai/monitoring/RasEventProviderHPCMSpec.groovy
> +import com.intel.runtime_utils.TimeUtils
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/test/groovy/com/intel/dai/monitoring/RasEventProviderForeignBusSpec.groovy
> +import com.intel.runtime_utils.TimeUtils
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/test/groovy/com/intel/dai/monitoring/EnvironmentalProviderHPCMSpec.groovy
> +import com.intel.runtime_utils.TimeUtils
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/test/groovy/com/intel/dai/monitoring/EnvironmentalProviderForeignBusSpec.groovy
> +import com.intel.runtime_utils.TimeUtils
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderHPCM.java
> +import com.intel.runtime_utils.TimeUtils;
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/main/java/com/intel/dai/monitoring/RasEventProviderForeignBus.java
> +import com.intel.runtime_utils.TimeUtils;
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on monitoring/src/main/java/com/intel/dai/monitoring/EventSimRasEventProviderForeignBus.java
> +import com.intel.runtime_utils.TimeUtils;
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on inventory/src/test/groovy/com/intel/dai/inventory/NetworkListenerProviderForeignBusSpec.groovy
> +import com.intel.runtime_utils.TimeUtils
Remove unused packages

2023-03-28 18:52 UTC, sindhu-106 commented on dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
> +                logMissingLocationEvent(eventName, nsTimestamp,  dataReceivedTimeStamp);
Its a system generated ras event use current timestamp.

2023-03-28 18:52 UTC, sindhu-106 commented on dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerSystemActions.java
>          lastMissingLocationNotification_.putIfAbsent(dataType, 0L);
Its a system generated ras event use current timestamp.

2023-03-28 18:52 UTC, sindhu-106 commented on dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
> +                        CommonDataFormat.setDataReceivedTimeStamp(TimeUtils.nanosecondsToMicroseconds(TimeUtils.getNsTimestamp()));
Why are using the current timestamp to set the data ?

2023-03-29 05:25 UTC, sindhu-106 requested changes

2023-03-29 05:25 UTC, sindhu-106 commented on dai_network_listener/src/main/java/com/intel/dai/network_listener/NetworkListenerCore.java
> +                        data.setDataReceivedTimeStamp(dataReceivedTimeStamp);
Timestamp value should be set before creating ras event

2023-03-29 05:25 UTC, sindhu-106 commented on monitoring/src/main/java/com/intel/dai/monitoring/EventSimRasEventProviderForeignBus.java
> +        //dataReceivedTimeStamp
remove commented lines

2023-03-29 05:25 UTC, sindhu-106 commented on networking/src/main/java/com/intel/networking/sink/for_benchmarking/NetworkDataSinkBenchmark.java
> +//TODO REPLACE "dataReceivedTimeStamp" WITH TimeUtils.nanosecondsToMicroseconds(TimeUtils.getNsTimestamp())
remove the commented lines

2023-03-29 05:25 UTC, sindhu-106 commented on networking/src/main/java/com/intel/networking/sink/for_benchmarking/NetworkDataSinkBenchmark.java
> +            callback_.processIncomingData(publishedSubject_, line, 0L);
Change 0L to current timestamp

2023-03-29 05:25 UTC, sindhu-106 commented on networking/src/main/java/com/intel/networking/sink/sse/NetworkDataSinkEventSource.java
> +            callback_.processIncomingData(event, message, 0L);
Use current timestamp instead of 0L

2023-03-29 05:25 UTC, sindhu-106 commented on procedures/src/test/java/com/intel/dai/procedures/RasEventStoreTest.java
> +                "RAS", 9999L, 0L);
Use current timestamp instead of 0L

2023-03-29 05:25 UTC, sindhu-106 commented on procedures/src/test/java/com/intel/dai/procedures/RasEventStoreTest.java
> +                "RAS", 9999L, 0L);
Use current timestamp instead of 0L

2023-03-29 05:25 UTC, sindhu-106 commented on procedures/src/test/java/com/intel/dai/procedures/RasEventStoreTest.java
> +                "RAS", 9999L, 0L);
Use current timestamp instead of 0L

2023-03-29 05:25 UTC, sindhu-106 commented on procedures/src/test/java/com/intel/dai/procedures/RasEventStoreTest.java
> +                "RAS", 9999L, 0L);
Use current timestamp instead of 0L

2023-03-29 05:25 UTC, sindhu-106 commented on procedures/src/test/java/com/intel/dai/procedures/RasEventStoreTest.java
> +                "RAS", 9999L, 0L);
Use current timestamp instead of 0L

2023-03-29 05:25 UTC, sindhu-106 commented on procedures/src/test/java/com/intel/dai/procedures/RasEventStoreTest.java
> +                "RAS", 9999L, 0L);
Use current timestamp instead of 0L

2023-03-30 02:07 UTC, sindhu-106 approved these changes

2023-03-30 17:52 UTC, sindhu-106 approved these changes

2023-04-03 20:54 UTC, sindhu-106 approved these changes

2023-04-03 21:01 UTC, anpatel1 approved these changes

2023-04-03 21:03 UTC, merged