[FEAT] Adding hostname info to event summary
unifiedcontrolsystem/dai-ds pull request #792
Opened 2023-03-27 21:19 UTC by sindhu-106

2023-03-27 21:24 UTC, anpatel1 requested changes

2023-03-27 21:29 UTC, anpatel1 requested changes

2023-03-27 21:29 UTC, anpatel1 commented on cli/cli/src/view_events_summary.py
> +            result += "{:<14} {:<14} {:<10} {:<70} {:<15} {:<20}\n".format(str(key[0]),
This needs to match with what you have above.

2023-03-27 21:39 UTC, anpatel1 approved these changes

2023-03-28 16:20 UTC, VanshIntel approved these changes

2023-03-28 16:40 UTC, merged